version: "3.7"

services:
  api:
    env_file: .env
    volumes:
      - /app/target
    build:
      context: ./actix-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./static/:/app/static
  nginx:
    build: ./nginx
    env_file: .env
    container_name: itf-days-dev-nginx
    volumes:
      - ./static/:/srv/app/static
    ports:
      - 8080:80
    restart: always
    depends_on:
      - api
      - react
  react:
    build: ./frontend
    container_name: itf-days-react
    command: sh -c "yarn install && yarn start"
    ports:
      - 3001:3000
    env_file:
      - ./.env
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/:/srv/app
      - /srv/app/node_modules
    depends_on:
      - api
    restart: on-failure
