version: "3.7"

services:
  api:
    env_file: .env
    build:
      context: ./actix-backend
      dockerfile: Dockerfile.dev
  nginx:
    build: ./nginx
    env_file: .env
    container_name: itf-days-dev-nginx
    volumes:
      - ./static/:/srv/app/static
    ports:
      - 8080:80
    restart: always
    depends_on:
      - api
