version: "3.7"

services:
  api:
    container_name: itf-days-api-prod
    build:
      context: ./actix-backend
      dockerfile: Dockerfile.prod
    env_file: .env
  nginx:
    ports:
      - 80:80
    depends_on:
      - api
